version: '3'
services:
    database-design:
        image: postgres:latest
        restart: always
        environment:
          - POSTGRES_DB=database-design-psql
          - POSTGRES_USER=postgres
          - POSTGRES_PASSWORD=docker
        logging:
          options:
            max-size: 10m
            max-file: "3"
        ports:
          - '5555:5432'
        volumes:
          - ./postgres-data:/var/lib/postgresql/data
          - ./database/schema/create_tables.sql:/docker-entrypoint-initdb.d/create_tables.sql
          - ./database/schema/migrations.sql:/docker-entrypoint-initdb.d/migrations.sql